name: esp_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  http: ^1.0.0
  intl: ^0.20.2
  pdf: ^3.10.4
  printing: ^5.10.4
  mqtt_client: ^10.5.1
  shared_preferences: ^2.2.0
  firebase_database: ^11.3.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/temp.svg
    - assets/icons/humidity.svg
    - assets/icons/co2.svg
    - assets/icons/smoke.svg
    - assets/icons/connection.svg
    - assets/icons/history.svg
    - assets/icons/my_health_icon.svg
    - assets/icons/nav_home.svg
    - assets/icons/nav_connection.svg
    - assets/icons/nav_history.svg
