name: esp_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  http: ^1.0.0
  intl: ^0.18.0
  pdf: ^3.10.4
  printing: ^5.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/temp.svg
    - assets/icons/humidity.svg
    - assets/icons/co2.svg
    - assets/icons/smoke.svg
    - assets/icons/connection.svg
    - assets/icons/history.svg
    - assets/icons/my_health_icon.svg
    - assets/icons/nav_home.svg
    - assets/icons/nav_connection.svg
    - assets/icons/nav_history.svg
