// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-6J2cr0QjN4meMBj4yHP2KoC51AzlE44',
    appId: '1:879705451691:web:9a8e80361f83714b50dbee',
    messagingSenderId: '879705451691',
    projectId: 'espcontrol-8de6a',
    authDomain: 'espcontrol-8de6a.firebaseapp.com',
    storageBucket: 'espcontrol-8de6a.firebasestorage.app',
    measurementId: 'G-TW7MNY2BGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUVnyRn2c91-_B8m0ermFJ3oT4f6_3T4o',
    appId: '1:879705451691:android:8d21ed87b9b0a93c50dbee',
    messagingSenderId: '879705451691',
    projectId: 'espcontrol-8de6a',
    storageBucket: 'espcontrol-8de6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQmCEGnYaoxSjgdLIzZdEMxgZ1EKBD_o',
    appId: '1:879705451691:ios:dd8404ab09599e6650dbee',
    messagingSenderId: '879705451691',
    projectId: 'espcontrol-8de6a',
    storageBucket: 'espcontrol-8de6a.firebasestorage.app',
    iosBundleId: 'com.example.espControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQmCEGnYaoxSjgdLIzZdEMxgZ1EKBD_o',
    appId: '1:879705451691:ios:dd8404ab09599e6650dbee',
    messagingSenderId: '879705451691',
    projectId: 'espcontrol-8de6a',
    storageBucket: 'espcontrol-8de6a.firebasestorage.app',
    iosBundleId: 'com.example.espControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-6J2cr0QjN4meMBj4yHP2KoC51AzlE44',
    appId: '1:879705451691:web:dee73d7c97f0721050dbee',
    messagingSenderId: '879705451691',
    projectId: 'espcontrol-8de6a',
    authDomain: 'espcontrol-8de6a.firebaseapp.com',
    storageBucket: 'espcontrol-8de6a.firebasestorage.app',
    measurementId: 'G-LN3BCQJMR6',
  );
}
